### ISSUE TITLE
Update PHP Doc Block - Says MongoDB

### ISSUE THREAD

**Issue by localpath** [kitar/laravel-dynamodb#27]
https://github.com/kitar/laravel-dynamodb/blob/e6c9063e368692cd22589b6791850a5010ae53ac/src/Kitar/Dynamodb/Connection.php#L70

**Comment by kitar** [comment]
Awthanks @localpath ! I didn't realize that.

**Comment by localpath** [comment]
@kitar NP. I noticed it after the new minor version. I use docker compose for local dev and my dynamoDB containers run using http so the minor version broke since I was using the shorthand reference from `.env` to the container. The new version adds `https` when I really just have `http` available by default on that container.

This breaks if you have dynamoDB locally running on http `DYNAMODB_ENDPOINT=dynamodb:8000`
Adding the protocol if you are on http fixes it `DYNAMODB_ENDPOINT=http://dynamodb:8000`

```
dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - 8042:8000
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    volumes:
      - deka-unified-dynamodb:/home/dynamodblocal/data
    user: root
    networks:
     - deka-unified
    restart: on-failure
```
